language: dart

dart:
  - dev
dart_task:
  # TODO: Only run dartfmt and dartanalyzer over dev release once Dart 2 stable is out
  - dartfmt
  - dartanalyzer
  - test

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
 directories:
   - $HOME/.pub-cache
