name: shelf_web_socket
version: 0.2.2+4

description: A WebSocket handler for Shelf.
author: Dart Team <misc@dartlang.org>
homepage: http://github.com/dart-lang/shelf_web_socket

environment:
  sdk: '>=2.0.0-dev.17.0 <3.0.0'

dependencies:
  shelf: '>=0.7.0 <0.8.0'
  stream_channel: ^1.4.0
  web_socket_channel: ^1.0.0

dev_dependencies:
  http: '>=0.10.0 <0.12.0'
  test: '>=0.12.42 <2.0.0'
