name: shelf_web_socket
version: 0.2.3

description: A WebSocket handler for Shelf.
author: Dart Team <misc@dartlang.org>
homepage: http://github.com/dart-lang/shelf_web_socket

environment:
  sdk: '>=2.0.0-dev.17.0 <3.0.0'

dependencies:
  shelf: ^0.7.3
  stream_channel: ^1.4.0
  web_socket_channel: ^1.0.0

dev_dependencies:
  http: ^0.11.3
  test: ^1.2.0
